version: '3.1'

services:

  db:
    network_mode: host
    image: postgres:11.1
    container_name: db 
    restart: always
    environment:
      POSTGRES_PASSWORD: sNoRjCyoKmPxh8pgk3M>zJ4cgBoeU8be
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  node:
    network_mode: host
    image: node:12
    container_name: node 
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: "npm run server"