version: '3.1'

services:

  db:
    image: postgres:11.1
    container_name: db 
    restart: always
    environment:
      POSTGRES_PASSWORD: sNoRjCyoKmPxh8pgk3M>zJ4cgBoeU8be
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  db_backup:
    image: postgres:11.1
    container_name: db_backup
    restart: always
    environment:
      POSTGRES_PASSWORD: sNoRjCyoKmPxh8pgk3M>zJ4cgBoeU8be
    volumes:
      - ./pgdata-backup:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5433

  node:
    image: node:10
    container_name: node 
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: "npm run dev"
    
  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "443:443"
      - "80:80"
    command: [nginx-debug, '-g', 'daemon off;']
